### ISSUE TITLE
Create partup auto scrolls too far

### ISSUE THREAD

**Issue by noelheesen** [part-up/part-up#927] opened 2017-02-28 14:34 UTC
When navigating to the create partup modal the input:name=partup_name gets focus, however the page get's scrolled way beyond the focussed input.

![create-partup-autoscroll-onnavigate](https://cloud.githubusercontent.com/assets/18031130/23409273/3d2e2d7e-fdcb-11e6-983f-f69dcbd76b84.png)

I have tried to fix this but couldn't find what caused the scrolling. My guess is that the 'AutoForm' library handles this but I could be wrong.

**Comment by ralphboeije** [comment] 2017-02-28 16:17
@andreleon could you maybe point Noel to the right place?

**Comment by ralphboeije** [comment] 2017-11-16 14:16
I can't reproduce this in production anymore, so I will close this one

**Closed by ralphboeije** 2017-11-16 14:16 UTC
Labels: Bug, Intermediate, Little work
