### ISSUE TITLE
Scroll bar user menu on Chrome displaced

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#171] opened 2016-01-14 10:08 UTC
See screenshot, scrollbar in user menu is not in the right position.

<img width="1440" alt="screen shot 2016-01-14 at 11 04 46" src="https://cloud.githubusercontent.com/assets/14044235/12321585/163f8736-baaf-11e5-880d-2fbe655d0ef1.png">

**Comment by ralphboeije** [comment] 2016-01-26 10:27
@tlimpanont this fix creates the issue with the tribe labels not showing on the user menu. This is the only blocker for the release. When do you have time to fix and deploy to production?

**Comment by ralphboeije** [comment] 2016-01-26 11:17
Here's a screen of the issue: 
<img width="1440" alt="screen shot 2016-01-26 at 12 16 48" src="https://cloud.githubusercontent.com/assets/14044235/12579230/b7558f28-c426-11e5-83f5-69e931b3792c.png">

**Comment by andreleon** [comment] 2016-02-26 14:59
@ralphboeije Why is this re-opened? I don't see any problems with the scrollbar in chrome

**Comment by ralphboeije** [comment] 2016-02-26 15:03
Hi @andreleon only on the user menu there was an issue. Maybe it is fixed in the latest version of chrome, since Theuy didn't see it today and I still do (haven't restarted chrome this week). In the screenshot you see the issue with the scroll bar only in the user menu.

<img width="1440" alt="screen shot 2016-02-26 at 16 01 49" src="https://cloud.githubusercontent.com/assets/14044235/13355793/6d41eaf0-dca2-11e5-96ee-f883e8456ee6.png">

**Comment by ralphboeije** [comment] 2016-02-29 07:45
Hi @andreleon and @tlimpanont I just checked and I still have the issue as in above screens while chrome is up to date. Can you both retest on you configs? 

<img width="1440" alt="screen shot 2016-02-29 at 08 43 43" src="https://cloud.githubusercontent.com/assets/14044235/13388495/b2991a7c-dec0-11e5-94ef-723173e6169a.png">

**Comment by andreleon** [comment] 2016-03-03 13:55
@ralphboeije I cannot reproduce this at all, and I have the same chrome version. Maybe the next time you're at Lifely we can look at it together

**Comment by ralphboeije** [comment] 2016-03-08 08:30
Yes, this is really strange, because I still have this issue and others also. Will check if Theuy also has it today so he can show you coming Friday when he is at Lifely.

**Comment by ralphboeije** [comment] 2016-03-12 19:29
@andreleon Thursday we saw that @LifelyPim also has this issue when he doesn't connect his mbp to an external display. Can you check with him to debug?

**Comment by andreleon** [comment] 2016-03-18 12:55
@ralphboeije I finally reproduced this issue
![screen shot 2016-03-18 at 13 28 25](https://cloud.githubusercontent.com/assets/1391492/13877819/7ade39cc-ed0d-11e5-8d97-394cf25233ea.png)

I determined it was a render bug in Chrome that only occurs on specific screen sizes(1440x900 in this case). We've encountered render issues before in Chrome and the fix(or hack) is always the same. By putting a 3d transform on the container we force Chrome to use hardware acceleration to render the specified element.
`transform: translateZ(0px); // enables hardware acceleration on the element`

As you can see below it is fixed with this "hack"
![screen shot 2016-03-18 at 13 28 34](https://cloud.githubusercontent.com/assets/1391492/13877909/13747c28-ed0e-11e5-9ae6-16071908992d.png)

**Comment by andreleon** [comment] 2016-03-18 12:56
Fixed in commit 0797a0b75098fd9cd00a564102f886e5bc0dc249

**Closed by andreleon** 2016-03-18 12:56 UTC
Labels: bug, User menu / notifications
