### ISSUE TITLE
1on1 chat keeps status 'unread'

### ISSUE THREAD

**Issue by eriksoon** [part-up/part-up#598] opened 2016-07-15 11:43 UTC
After reading a 1on1 chat the blue line (new discussion) often disappears, but the number of unread items stays. This makes also that the orange notifier on the chat keeps on showing.

Windows 10, Chrome

![image](https://cloud.githubusercontent.com/assets/18055074/16873216/1081a73e-4a92-11e6-8e0f-eb9ff0ca777a.png)

**Comment by andreleon** [comment] 2016-08-09 13:08
@ralphboeije This issue was fixed in commit 9a38da025118d3c8b2b7725fc82c6000c4651daf 2 weeks ago. With the deployment of version 1.21.3 it was fixed in production as well. Also this issue is a duplicate of #590 Or it is at least related.

**Comment by ralphboeije** [comment] 2016-08-10 09:17
@andreleon This issue was reported and shown to me after the release of 1.21.3. I haven't consistently reproduced it though, so let's ask @eriksoon when he is back from holiday.

**Comment by ralphboeije** [comment] 2016-08-11 07:46
@andreleon just saw the issue again, see screenshots.

<img width="1440" alt="screen shot 2016-08-11 at 09 06 32" src="https://cloud.githubusercontent.com/assets/14044235/17581759/f63d7e04-5fa7-11e6-91b3-dca440112aff.png">
<img width="1440" alt="screen shot 2016-08-11 at 09 06 40" src="https://cloud.githubusercontent.com/assets/14044235/17581758/f6385c58-5fa7-11e6-9ca7-fafa0c6a8aee.png">

**Comment by ralphboeije** [comment] 2016-08-11 07:47
Still showing after I had a chat with you and Ilan and visited some other pages on Part-up.

<img width="1440" alt="screen shot 2016-08-11 at 09 46 30" src="https://cloud.githubusercontent.com/assets/14044235/17581861/92b5ba26-5fa8-11e6-9465-3d91bd4da5f7.png">

**Closed** 2016-08-16 19:14 UTC
Labels: bug
