### ISSUE TITLE
Long tag on most right column part-up tile on discover doesn't hide behind tile

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#295] opened 2016-03-17 14:59 UTC
To reproduce:
1. Create four part-ups with long tags
2. Go to discover and select newest filter
3. Hoover the most right part-up on the first row (4th column) and see the tags come out on the left side
4. Un-hoover and see a part of the long tags come out on the left side of the tile
5. Hoover the 3rd part-up in this row and see that there is a strange cutout on the tags where it overlaps the tags that come out on the left side of the 4th tile

<img width="1440" alt="screen shot 2016-03-17 at 15 39 50" src="https://cloud.githubusercontent.com/assets/14044235/13850178/32e1704e-ec59-11e5-92bd-360a977bef4a.png">

**Comment by andreleon** [comment] 2016-08-10 08:11
This issue was resolved long ago, so I'm closing this issue since I cannot reproduce this anymore

**Closed by andreleon** 2016-08-10 08:11 UTC
Labels: bug
